

name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set Docker Build
      uses: docker/setup-buildx-action@v2.5.0
    
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: micaeloliveiradev
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKERHUB }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v4.0.0
      with:
        context: .
        file: ./Dockerfile          
        push: true
        tags: micaeloliveiradev/go_ci:${{github.ref_name}}


